import ReactHead from "next/head";

export function Head() {
 return (
  <ReactHead>
   <title>Quản lý vật liệu Thành Tân</title>
   <meta name="description" content="Generated by create next app" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link rel="icon" href="/favicon.ico" />
  </ReactHead>
 );
}
